// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMQAcg-aQ68aJ1Jv0pselnVn5pxr8v2c',
    appId: '1:41473756967:web:b4794bd774a5a8c80f2302',
    messagingSenderId: '41473756967',
    projectId: 'website-37264',
    authDomain: 'website-37264.firebaseapp.com',
    storageBucket: 'website-37264.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4x3cZihcrlTB4drCR987HhW4_IxnWWho',
    appId: '1:41473756967:android:7f5d9572f4a4cbd60f2302',
    messagingSenderId: '41473756967',
    projectId: 'website-37264',
    storageBucket: 'website-37264.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMQAcg-aQ68aJ1Jv0pselnVn5pxr8v2c',
    appId: '1:41473756967:web:b4794bd774a5a8c80f2302',
    messagingSenderId: '41473756967',
    projectId: 'website-37264',
    authDomain: 'website-37264.firebaseapp.com',
    storageBucket: 'website-37264.firebasestorage.app',
  );
}
